### ISSUE TITLE
I can run

### ISSUE THREAD

**Issue by bordik** [zcharli/posdb#6]
I did everything as instructed but can't start.
Plz help

**Comment by bordik** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.4
3 info using node@v13.12.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle posdb@0.0.0~prestart: posdb@0.0.0
6 info lifecycle posdb@0.0.0~start: posdb@0.0.0
7 verbose lifecycle posdb@0.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle posdb@0.0.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/user/posdb/node_modules/.bin:/home/user/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
9 verbose lifecycle posdb@0.0.0~start: CWD: /home/user/posdb
10 silly lifecycle posdb@0.0.0~start: Args: [ '-c', 'node ./bin/www' ]
11 silly lifecycle posdb@0.0.0~start: Returned: code: 1  signal: null
12 info lifecycle posdb@0.0.0~start: Failed to exec start script
13 verbose stack Error: posdb@0.0.0 start: `node ./bin/www`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1026:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid posdb@0.0.0
15 verbose cwd /home/user/posdb
16 verbose Linux 5.4.24-1-MANJARO
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v13.12.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error posdb@0.0.0 start: `node ./bin/www`
22 error Exit status 1
23 error Failed at the posdb@0.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
